# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbf00890120dbaa9e045a5017325a3bbf91daa6aff33c831fb26b0bcc0e6f710827da4333f567d60049ee9f8833058ffcf8e75e0118248446cb3ddfdbb69117

test:
  secret_key_base: d3de1e0c59bce947f0a0d49f6443575416abb6fa24f3abb855a9d957a1e92e3882f10b8ce798d179ef925e3e411a661abf7d11be7601ea28da75b365cc0f3714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
